import type { SeedMock } from "../seed-types";

// UPSC Prelims CSAT (GS Paper II) mock series — starter question bank.
// Real pattern (stable for years): 80 questions, 200 marks (2.5 each),
// 2 hours, one-third negative marking (−0.833 per wrong), QUALIFYING at 33%.
// Comprehension answers here depend ONLY on the passage text (CSAT style);
// passages are original Bodhi text, so there is no copyright issue.

const COMP = "Comprehension";
const REAS = "Logical Reasoning & Analytical Ability";
const NUM = "Basic Numeracy & Data Interpretation";

const PASSAGE_1 = `Read the passage: "India draws more groundwater every year than any other country, and most of it irrigates farms. When extraction outpaces natural recharge, water tables fall, wells run deeper and costlier, and small farmers suffer first. Studies of drip irrigation in water-scarce districts show that delivering water directly to plant roots can cut water use sharply without reducing yields. Yet adoption remains low, because the upfront equipment cost is high even where subsidies exist." — `;

const PASSAGE_2 = `Read the passage: "Digital payments have spread rapidly in India because they solved a real problem: small transactions needed exact change, and cash handling carried costs for shopkeepers. Once smartphone QR codes made accepting payment free and instant, even roadside vendors joined. However, the same convenience creates a new risk — users who cannot read warning messages carefully can be tricked into approving transfers they did not intend. Convenience and caution must grow together." — `;

const PASSAGE_3 = `Read the passage: "Rooftop solar panels can cut a household's electricity bill by a large margin, and the government offers a subsidy to make installation cheaper. Even so, uptake in most cities remains low. Surveys of homeowners show that many simply do not know the subsidy exists, and those who do often distrust unfamiliar installers after hearing of poor-quality panels sold without proper warranties. Where a housing society has arranged a single trusted vendor for the whole building, installation rates have been far higher than in buildings left to individual owners." — `;

const PASSAGE_4 = `Read the passage: "Public libraries were once judged mainly by the number of books on their shelves. Today, many library planners judge them instead by footfall — how many people actually walk in. A library in a mid-sized town doubled its daily visitors after adding free Wi-Fi, comfortable seating, and a children's reading corner, without buying many new books. This suggests that for a large share of visitors, a library's value lies as much in being a welcoming shared space as in the books it holds — though committed readers still come chiefly for the collection itself." — `;

const PASSAGE_5 = `Read the passage: "A city widened a congested arterial road, adding two extra lanes in each direction, expecting faster commutes. Within two years, traffic speeds during peak hours were back to where they had been before the widening, even though more vehicles were now using the road. Transport planners call this induced demand: extra road space encourages more people to drive, until congestion returns to roughly its earlier level. Cities that instead added a dedicated bus lane on the same stretch saw peak-hour bus ridership rise sharply, without needing to widen the road at all." — `;

export const upscCsatMock: SeedMock = {
  slug: "upsc-prelims-csat-mock-series",
  title: "UPSC Prelims CSAT (Paper II) — Mock Series",
  description:
    "Simulation of UPSC Prelims CSAT: comprehension, logical reasoning, and basic numeracy on the real pattern — 80 questions, 2 hours, +2.5 / −0.83 marking (qualifying paper: 33% needed in the real exam). One payment unlocks the full series; papers are composed from a growing verified question bank.",
  price_inr: 249,
  exam_minutes: 120,
  marks_correct: 2.5,
  marks_wrong: 2.5 / 3,
  paper_count: 1000,
  paper_size: 80,
  subject_quota: { [COMP]: 26, [REAS]: 30, [NUM]: 24 },
  questions: [
    // ---------------- Basic Numeracy (14) ----------------
    { q: "What is the HCF of 24 and 36?", options: ["6", "8", "12", "18"], correct: 2, subject: NUM, explanation: "24 = 2³×3, 36 = 2²×3²; common factors give 2²×3 = 12." },
    { q: "What is 15% of 240?", options: ["30", "32", "36", "40"], correct: 2, subject: NUM, explanation: "10% of 240 is 24 and 5% is 12; together 36." },
    { q: "₹75 is divided between two people in the ratio 2 : 3. The smaller share is:", options: ["₹25", "₹30", "₹35", "₹45"], correct: 1, subject: NUM, explanation: "Five equal parts of ₹15 each; the smaller share is 2 × 15 = ₹30." },
    { q: "The average of 12, 18, and 24 is:", options: ["16", "17", "18", "20"], correct: 2, subject: NUM, explanation: "Sum 54 divided by 3 gives 18 (also the middle value of an evenly spaced list)." },
    { q: "A 120 m long train travelling at 36 km/h passes a pole in:", options: ["10 seconds", "12 seconds", "15 seconds", "18 seconds"], correct: 1, subject: NUM, explanation: "36 km/h = 10 m/s; time = 120/10 = 12 seconds." },
    { q: "A finishes a work in 10 days and B in 15 days. Together they finish it in:", options: ["5 days", "6 days", "7 days", "8 days"], correct: 1, subject: NUM, explanation: "1/10 + 1/15 = 1/6 of the work per day, so 6 days." },
    { q: "Simple interest on ₹4,000 at 6% per annum for 2 years is:", options: ["₹440", "₹460", "₹480", "₹500"], correct: 2, subject: NUM, explanation: "SI = 4000 × 6 × 2 / 100 = ₹480." },
    { q: "The smallest three-digit number divisible by 7 is:", options: ["100", "102", "105", "112"], correct: 2, subject: NUM, explanation: "7 × 15 = 105; 7 × 14 = 98 has only two digits." },
    { q: "The probability of getting a head in a single toss of a fair coin is:", options: ["1/4", "1/3", "1/2", "1"], correct: 2, subject: NUM, explanation: "Two equally likely outcomes, one favourable: probability 1/2." },
    { q: "In how many different orders can 4 distinct books be arranged on a shelf?", options: ["12", "16", "24", "32"], correct: 2, subject: NUM, explanation: "4! = 4 × 3 × 2 × 1 = 24 arrangements." },
    { q: "An article bought for ₹250 is sold for ₹300. The profit percentage is:", options: ["15%", "18%", "20%", "25%"], correct: 2, subject: NUM, explanation: "Profit ₹50 on cost ₹250 = 50/250 = 20%." },
    { q: "If 5 pens cost ₹60, what do 8 such pens cost?", options: ["₹90", "₹92", "₹96", "₹100"], correct: 2, subject: NUM, explanation: "One pen costs ₹12, so 8 pens cost ₹96." },
    { q: "A 40-litre mixture has milk and water in the ratio 3 : 1. The quantity of milk is:", options: ["25 litres", "28 litres", "30 litres", "32 litres"], correct: 2, subject: NUM, explanation: "Milk is 3/4 of 40 litres = 30 litres." },
    { q: "Successive increases of 10% and 20% are equivalent to a single increase of:", options: ["30%", "31%", "32%", "33%"], correct: 2, subject: NUM, explanation: "1.10 × 1.20 = 1.32, a 32% overall increase — not 30%." },
    { q: "What is the LCM of 12 and 18?", options: ["24", "36", "54", "72"], correct: 1, subject: NUM, explanation: "12 = 2²×3, 18 = 2×3²; LCM takes the highest powers: 2²×3² = 36." },
    { q: "What is 25% of 320?", options: ["70", "75", "80", "85"], correct: 2, subject: NUM, explanation: "A quarter of 320 is 80." },
    { q: "₹120 is divided between two people in the ratio 3 : 5. The larger share is:", options: ["₹60", "₹70", "₹75", "₹80"], correct: 2, subject: NUM, explanation: "Eight equal parts of ₹15 each; the larger share is 5 × 15 = ₹75." },
    { q: "The average of 10, 20, 30, and 40 is:", options: ["20", "25", "30", "35"], correct: 1, subject: NUM, explanation: "Sum 100 divided by 4 gives 25." },
    { q: "A 150 m long train travelling at 54 km/h passes a pole in:", options: ["8 seconds", "10 seconds", "12 seconds", "15 seconds"], correct: 1, subject: NUM, explanation: "54 km/h = 15 m/s; time = 150/15 = 10 seconds." },
    { q: "A finishes a work in 12 days and B in 24 days. Together they finish it in:", options: ["6 days", "7 days", "8 days", "9 days"], correct: 2, subject: NUM, explanation: "1/12 + 1/24 = 1/8 of the work per day, so 8 days." },
    { q: "Simple interest on ₹5,000 at 8% per annum for 3 years is:", options: ["₹1,000", "₹1,100", "₹1,200", "₹1,300"], correct: 2, subject: NUM, explanation: "SI = 5000 × 8 × 3 / 100 = ₹1,200." },
    { q: "The smallest four-digit number divisible by 9 is:", options: ["1,000", "1,002", "1,008", "1,010"], correct: 2, subject: NUM, explanation: "9 × 112 = 1,008 is the first multiple of 9 at or above 1,000." },
    { q: "A standard deck has 52 cards. The probability of drawing a king is:", options: ["1/13", "1/12", "1/26", "1/4"], correct: 0, subject: NUM, explanation: "There are 4 kings among 52 cards: 4/52 = 1/13." },
    { q: "In how many different orders can the 4 letters of the word MATH be arranged?", options: ["12", "20", "24", "28"], correct: 2, subject: NUM, explanation: "4! = 4 × 3 × 2 × 1 = 24 arrangements." },
    { q: "An article bought for ₹400 is sold for ₹460. The profit percentage is:", options: ["10%", "12%", "15%", "18%"], correct: 2, subject: NUM, explanation: "Profit ₹60 on cost ₹400 = 60/400 = 15%." },
    { q: "If 7 notebooks cost ₹210, what do 12 such notebooks cost?", options: ["₹340", "₹350", "₹360", "₹370"], correct: 2, subject: NUM, explanation: "One notebook costs ₹30, so 12 notebooks cost ₹360." },
    { q: "A 50-litre mixture has milk and water in the ratio 2 : 3. The quantity of water is:", options: ["15 litres", "20 litres", "25 litres", "30 litres"], correct: 3, subject: NUM, explanation: "Water is 3/5 of 50 litres = 30 litres." },
    { q: "Successive discounts of 20% and 10% are equivalent to a single discount of:", options: ["28%", "30%", "32%", "27%"], correct: 0, subject: NUM, explanation: "0.80 × 0.90 = 0.72, a 28% overall discount — not the simple sum of 30%." },
    { q: "3/4 expressed as a percentage is:", options: ["65%", "70%", "75%", "80%"], correct: 2, subject: NUM, explanation: "3 ÷ 4 = 0.75 = 75%." },
    { q: "A sum doubles itself in 8 years on simple interest. The annual rate of interest is:", options: ["10%", "12.5%", "15%", "20%"], correct: 1, subject: NUM, explanation: "Doubling means SI equals the principal: P = P × R × 8 / 100, so R = 100/8 = 12.5%." },
    { q: "Two numbers are in the ratio 4 : 5 and their sum is 90. The smaller number is:", options: ["36", "40", "45", "50"], correct: 1, subject: NUM, explanation: "Nine equal parts of 10 each; the smaller number is 4 × 10 = 40." },
    { q: "What comes next in the series: 2, 5, 10, 17, 26, ?", options: ["35", "36", "37", "38"], correct: 2, subject: NUM, explanation: "Differences are 3, 5, 7, 9 — consecutive odd numbers — so the next difference is 11, giving 37." },
    { q: "The perimeter of a square is 48 cm. Its area is:", options: ["100 cm²", "121 cm²", "144 cm²", "169 cm²"], correct: 2, subject: NUM, explanation: "Side = 48/4 = 12 cm; area = 12² = 144 cm²." },
    { q: "A shopkeeper marks an item 25% above cost price and then gives a 10% discount on the marked price. His profit percentage is:", options: ["10%", "12.5%", "15%", "20%"], correct: 1, subject: NUM, explanation: "On a cost of 100, marked price is 125; after a 10% discount the selling price is 112.5 — a profit of 12.5%." },

    // ---------------- Logical Reasoning (14) ----------------
    { q: "What comes next in the series: 3, 6, 11, 18, 27, ?", options: ["36", "38", "40", "42"], correct: 1, subject: REAS, explanation: "Differences are 3, 5, 7, 9 — consecutive odd numbers — so the next difference is 11 and the answer is 38." },
    { q: "What comes next in the series: B, D, G, K, ?", options: ["N", "O", "P", "Q"], correct: 2, subject: REAS, explanation: "Steps of +2, +3, +4, +5: B(2), D(4), G(7), K(11), P(16)." },
    { q: "If CAT is coded as DBU, how is DOG coded?", options: ["EPH", "EPI", "FPH", "EQH"], correct: 0, subject: REAS, explanation: "Each letter moves one step forward: D→E, O→P, G→H." },
    { q: "A is the brother of B. B is the mother of C. How is A related to C?", options: ["Father", "Uncle", "Brother", "Grandfather"], correct: 1, subject: REAS, explanation: "A is the brother of C's mother, which makes A the maternal uncle of C." },
    { q: "A man walks 5 km east, turns left and walks 3 km, then turns left and walks 5 km. Where is he relative to his start?", options: ["3 km east", "3 km north", "3 km west", "At the start"], correct: 1, subject: REAS, explanation: "The two 5-km legs (east, then west) cancel; the middle leg after the first left turn from east heads north, leaving him 3 km north." },
    { q: "In a row, Sita is 12th from the left end and 8th from the right end. How many people are in the row?", options: ["18", "19", "20", "21"], correct: 1, subject: REAS, explanation: "Total = 12 + 8 − 1 = 19 (Sita is counted from both ends)." },
    { q: "Find the odd one out: circle, triangle, square, cube.", options: ["Circle", "Triangle", "Square", "Cube"], correct: 3, subject: REAS, explanation: "Circle, triangle, and square are plane (2-D) figures; a cube is a solid (3-D)." },
    { q: "Statements: All roses are flowers. Some flowers fade quickly. Does the conclusion 'Some roses fade quickly' follow?", options: ["Yes", "No", "Only in summer", "The statements contradict each other"], correct: 1, subject: REAS, explanation: "The quickly-fading flowers need not include any roses, so the conclusion does not necessarily follow." },
    { q: "What is the angle between the two hands of a clock at exactly 6:00?", options: ["90°", "120°", "150°", "180°"], correct: 3, subject: REAS, explanation: "At 6:00 the hour hand points at 6 and the minute hand at 12 — exactly opposite, 180°." },
    { q: "What comes next: 1, 1, 2, 3, 5, 8, ?", options: ["11", "12", "13", "15"], correct: 2, subject: REAS, explanation: "Each term is the sum of the previous two (Fibonacci): 5 + 8 = 13." },
    { q: "If MONDAY is coded as 123456 (M=1, O=2, N=3, D=4, A=5, Y=6), what is the code for DAY?", options: ["456", "465", "546", "645"], correct: 0, subject: REAS, explanation: "D=4, A=5, Y=6, so DAY = 456." },
    { q: "Among five people, D is the tallest and E is the shortest. A is taller than B, and B is taller than C. Who is exactly in the middle by height?", options: ["A", "B", "C", "Cannot be determined"], correct: 1, subject: REAS, explanation: "The order is D > A > B > C > E, so B is third of five — the middle." },
    { q: "On a standard die, opposite faces add up to 7. If 2 is on top, which number is at the bottom?", options: ["3", "4", "5", "6"], correct: 2, subject: REAS, explanation: "Opposite faces sum to 7, so the face opposite 2 is 5." },
    { q: "How many times does the letter S appear in the word STATISTICS?", options: ["2", "3", "4", "5"], correct: 1, subject: REAS, explanation: "S-T-A-T-I-S-T-I-C-S: the letter S occurs at positions 1, 6, and 10 — three times." },
    { q: "What comes next in the series: 4, 8, 16, 32, ?", options: ["48", "56", "64", "72"], correct: 2, subject: REAS, explanation: "Each term doubles the previous one: 32 × 2 = 64." },
    { q: "What comes next in the series: A, C, F, J, ?", options: ["N", "O", "P", "Q"], correct: 1, subject: REAS, explanation: "Steps of +2, +3, +4, +5: A(1), C(3), F(6), J(10), O(15)." },
    { q: "If ROSE is coded as SPTF (each letter shifted one step forward), how is LOTUS coded?", options: ["MPUVT", "MPVUT", "NPUVT", "MPUVS"], correct: 0, subject: REAS, explanation: "Shifting each letter forward by one: L→M, O→P, T→U, U→V, S→T, giving MPUVT." },
    { q: "P is the sister of Q. Q is the son of R. How is P related to R?", options: ["Daughter", "Sister", "Niece", "Mother"], correct: 0, subject: REAS, explanation: "Since Q is R's child and P is Q's sibling, P is also R's child — a daughter." },
    { q: "A man walks 4 km north, turns right and walks 3 km, then turns right and walks 4 km. How far and in which direction is he from his start?", options: ["3 km east", "3 km west", "7 km east", "5 km north"], correct: 0, subject: REAS, explanation: "The two 4-km legs (north, then south) cancel out; the middle leg after the first right turn heads east, leaving him 3 km east." },
    { q: "In a queue, Ravi is 15th from the front and 9th from the back. How many people are in the queue?", options: ["22", "23", "24", "25"], correct: 1, subject: REAS, explanation: "Total = 15 + 9 − 1 = 23 (Ravi is counted from both ends)." },
    { q: "Find the odd one out: apple, banana, potato, mango.", options: ["Apple", "Banana", "Potato", "Mango"], correct: 2, subject: REAS, explanation: "Apple, banana, and mango are fruits; a potato is a vegetable." },
    { q: "Statements: All cats are animals. Some animals are wild. Does the conclusion 'Some cats are wild' follow?", options: ["Yes", "No", "Cannot be determined", "Always true"], correct: 1, subject: REAS, explanation: "The wild animals need not include any cats, so the conclusion does not necessarily follow." },
    { q: "What is the angle between the hour and minute hands of a clock at exactly 3:00?", options: ["60°", "75°", "90°", "105°"], correct: 2, subject: REAS, explanation: "At 3:00 the hour hand is at the 3 mark and the minute hand at 12 — a quarter turn apart, 90°." },
    { q: "What comes next: 2, 3, 5, 8, 13, ?", options: ["18", "19", "20", "21"], correct: 3, subject: REAS, explanation: "Each term is the sum of the previous two: 8 + 13 = 21." },
    { q: "If TIGER is coded as UJHFS (each letter shifted one step forward), what is the code for LIONS?", options: ["MJPOT", "MJPPT", "NJPOT", "MJPOS"], correct: 0, subject: REAS, explanation: "Shifting each letter forward by one: L→M, I→J, O→P, N→O, S→T, giving MJPOT." },
    { q: "Among five friends, E is the tallest and F is the shortest. G is taller than H, and H is taller than I. Who is exactly in the middle by height?", options: ["G", "H", "I", "F"], correct: 1, subject: REAS, explanation: "The order is E > G > H > I > F, so H is third of five — the middle." },
    { q: "On a standard die, opposite faces add up to 7. If 3 is on top, which number is at the bottom?", options: ["2", "3", "4", "5"], correct: 2, subject: REAS, explanation: "Opposite faces sum to 7, so the face opposite 3 is 4." },
    { q: "How many times does the letter A appear in the word BANANA?", options: ["2", "3", "4", "5"], correct: 1, subject: REAS, explanation: "B-A-N-A-N-A: the letter A occurs at positions 2, 4, and 6 — three times." },
    { q: "What comes next in the series: 5, 10, 20, 40, ?", options: ["60", "70", "80", "90"], correct: 2, subject: REAS, explanation: "Each term doubles the previous one: 40 × 2 = 80." },
    { q: "If in a code language GARDEN is written as HBSEFO (each letter shifted one step forward), how is FLOWER written?", options: ["GMPXFS", "GMPXFR", "GMQXFS", "HMPXFS"], correct: 0, subject: REAS, explanation: "Shifting each letter forward by one: F→G, L→M, O→P, W→X, E→F, R→S, giving GMPXFS." },
    { q: "A is the father of B. C is the sister of B. How is C related to A?", options: ["Daughter", "Wife", "Sister", "Mother"], correct: 0, subject: REAS, explanation: "C is a child of A, and specifically a daughter." },
    { q: "Find the missing number: 7, 14, 28, 56, ?", options: ["98", "104", "112", "120"], correct: 2, subject: REAS, explanation: "Each term doubles the previous one: 56 × 2 = 112." },
    { q: "If day 1 is a Monday, what day of the week is day 17?", options: ["Tuesday", "Wednesday", "Thursday", "Friday"], correct: 1, subject: REAS, explanation: "Day 15 falls exactly two weeks after day 1, so it is also a Monday; day 16 is Tuesday and day 17 is Wednesday." },
    { q: "Statements: All pens are pencils. All pencils are erasers. Does the conclusion 'All pens are erasers' follow?", options: ["Yes, it follows", "No, it doesn't follow", "Cannot be determined", "Only some pens are erasers"], correct: 0, subject: REAS, explanation: "This is a straightforward chain: if every pen is a pencil and every pencil is an eraser, every pen is an eraser." },

    // ---------------- Comprehension (8): answers come ONLY from the passages ----------------
    { q: PASSAGE_1 + "What is the main concern of the passage?", options: ["India imports too much water", "Groundwater extraction exceeding recharge and its consequences", "Farmers refuse to irrigate their fields", "Urban water parks waste water"], correct: 1, subject: COMP, explanation: "The passage centres on over-extraction of groundwater, falling water tables, and a possible remedy." },
    { q: PASSAGE_1 + "According to the passage, when extraction outpaces recharge:", options: ["Yields immediately rise", "Water tables fall and wells become deeper and costlier", "Rainfall decreases", "Subsidies are withdrawn"], correct: 1, subject: COMP, explanation: "The passage states this directly: water tables fall, wells run deeper and costlier." },
    { q: PASSAGE_1 + "What does the passage say about drip irrigation?", options: ["It reduces yields", "It cuts water use sharply without reducing yields", "It is banned in water-scarce districts", "It increases recharge of aquifers"], correct: 1, subject: COMP, explanation: "Studies cited in the passage show sharp water savings with no yield loss." },
    { q: PASSAGE_1 + "Which of the following can be inferred as the main barrier to drip-irrigation adoption?", options: ["Farmers do not trust studies", "High upfront equipment cost", "Government prohibition", "Lack of smartphones"], correct: 1, subject: COMP, explanation: "The passage attributes low adoption to high upfront cost, 'even where subsidies exist'." },
    { q: PASSAGE_2 + "According to the passage, digital payments spread rapidly in India because they:", options: ["Were made legally compulsory", "Solved real problems of exact change and cash-handling costs", "Offered high interest rates", "Were free of all risk"], correct: 1, subject: COMP, explanation: "The passage names the exact-change problem and shopkeepers' cash-handling costs as the solved problems." },
    { q: PASSAGE_2 + "What role did QR codes play, as per the passage?", options: ["They made accepting payment free and instant", "They increased the cost of transactions", "They replaced bank accounts", "They eliminated all fraud"], correct: 0, subject: COMP, explanation: "The passage says smartphone QR codes made accepting payment free and instant, bringing in even roadside vendors." },
    { q: PASSAGE_2 + "The new risk described in the passage is that users may:", options: ["Lose network connectivity", "Be tricked into approving unintended transfers if they do not read warnings carefully", "Pay higher taxes", "Forget their passwords"], correct: 1, subject: COMP, explanation: "The passage warns that careless reading of warning messages can lead to approving unintended transfers." },
    { q: PASSAGE_2 + "The concluding sentence 'convenience and caution must grow together' most nearly means:", options: ["Convenience should be abandoned", "Safety awareness must keep pace with ease of use", "Caution makes payments slower and should be reduced", "Only cash is safe"], correct: 1, subject: COMP, explanation: "The author argues that as payments get easier, users' carefulness must increase alongside — not that convenience is bad." },

    { q: PASSAGE_3 + "What is the main concern of the passage?", options: ["Solar panels are too expensive even with a subsidy", "Awareness gaps and distrust of installers limit rooftop solar adoption despite a subsidy", "The government has stopped offering solar subsidies", "Housing societies are banned from installing solar panels"], correct: 1, subject: COMP, explanation: "The passage centres on low uptake caused by lack of awareness of the subsidy and distrust of installers." },
    { q: PASSAGE_3 + "According to the passage, why do many homeowners not install solar panels?", options: ["They cannot afford electricity bills", "They do not know about the subsidy or distrust unfamiliar installers", "Their rooftops are structurally unsound", "Local laws prohibit installation"], correct: 1, subject: COMP, explanation: "The passage names exactly these two reasons: lack of awareness of the subsidy and distrust of installers." },
    { q: PASSAGE_3 + "What has led to higher installation rates in some buildings, as per the passage?", options: ["Free installation by the government", "A housing society arranging one trusted vendor for the whole building", "Mandatory installation rules", "Lower panel prices in those cities"], correct: 1, subject: COMP, explanation: "The passage attributes higher rates to a single trusted vendor arranged for the whole building." },
    { q: PASSAGE_3 + "What can be inferred about panels sold without warranties?", options: ["They perform better than warrantied ones", "They have contributed to homeowner distrust of installers", "They are illegal to sell", "They are always more expensive"], correct: 1, subject: COMP, explanation: "The passage links poor-quality, unwarrantied panels to the distrust homeowners report." },
    { q: PASSAGE_3 + "The word 'uptake' in the passage most nearly means:", options: ["Removal", "Adoption or take-up", "Price increase", "Repair"], correct: 1, subject: COMP, explanation: "In context, 'uptake' refers to how many people take up or adopt the panels." },
    { q: PASSAGE_3 + "The passage suggests that individual owners installing solar on their own, compared with a housing-society-arranged vendor, tend to:", options: ["Install at a similar rate", "Install at a lower rate", "Install at a much higher rate", "Always choose government vendors"], correct: 1, subject: COMP, explanation: "The passage says installation rates have been far higher where a society arranged one vendor than in buildings left to individual owners." },
    { q: PASSAGE_3 + "Which of the following best describes the government's role as per the passage?", options: ["Directly installing panels for free", "Offering a subsidy to reduce installation cost", "Banning private installers", "Fixing electricity prices"], correct: 1, subject: COMP, explanation: "The passage states the government offers a subsidy to make installation cheaper." },
    { q: PASSAGE_3 + "The passage is primarily concerned with explaining:", options: ["The technical working of solar panels", "Factors affecting adoption of a technology despite a cost incentive", "A comparison of Indian and foreign solar markets", "The history of electricity subsidies"], correct: 1, subject: COMP, explanation: "Throughout, the passage examines why adoption stays low despite the subsidy — i.e., factors affecting adoption." },

    { q: PASSAGE_4 + "What is the main point of the passage?", options: ["Libraries should stop buying books", "A library's value today includes being a welcoming shared space, not just its book collection", "Footfall does not matter for libraries", "Children should not use libraries"], correct: 1, subject: COMP, explanation: "The passage argues library value now includes being a welcoming space, alongside the collection." },
    { q: PASSAGE_4 + "According to the passage, what caused the town library's visitor numbers to double?", options: ["A large new shipment of books", "Free Wi-Fi, comfortable seating, and a children's reading corner", "Lower membership fees", "A new building"], correct: 1, subject: COMP, explanation: "The passage names these three additions as the cause, without buying many new books." },
    { q: PASSAGE_4 + "The passage states that committed readers come to the library chiefly for:", options: ["Free Wi-Fi", "Comfortable seating", "The book collection itself", "The children's reading corner"], correct: 2, subject: COMP, explanation: "The passage closes by noting committed readers still come chiefly for the collection itself." },
    { q: PASSAGE_4 + "The word 'footfall' in the passage most nearly means:", options: ["Number of visitors", "Number of books", "Library budget", "Floor area"], correct: 0, subject: COMP, explanation: "The passage defines footfall as how many people actually walk in." },
    { q: PASSAGE_4 + "What can be inferred about the old way of judging libraries?", options: ["It considered comfortable seating important", "It focused mainly on the number of books on shelves", "It ignored books entirely", "It always emphasised Wi-Fi"], correct: 1, subject: COMP, explanation: "The passage opens by saying libraries were once judged mainly by the number of books on their shelves." },
    { q: PASSAGE_4 + "Which group, per the passage, values the library mainly for its book collection?", options: ["Children", "Casual visitors", "Committed readers", "Wi-Fi users"], correct: 2, subject: COMP, explanation: "The passage specifically names committed readers as coming chiefly for the collection." },
    { q: PASSAGE_4 + "The example of the mid-sized town library is used to:", options: ["Prove that books are no longer needed in libraries", "Illustrate that non-book amenities can significantly raise footfall", "Show that children's corners are unpopular", "Argue for closing under-used libraries"], correct: 1, subject: COMP, explanation: "The example directly illustrates how non-book amenities doubled visitor footfall." },
    { q: PASSAGE_4 + "Which statement best fits the passage's overall tone?", options: ["Books are now irrelevant to libraries", "Both welcoming amenities and the book collection contribute to a library's value", "Only technology matters in modern libraries", "Library planners should ignore footfall"], correct: 1, subject: COMP, explanation: "The passage balances both factors, closing by affirming the collection still matters to committed readers." },

    { q: PASSAGE_5 + "What is the main idea of the passage?", options: ["Wider roads always cure congestion permanently", "Widening roads can be undone by induced demand, while a dedicated bus lane raised ridership without widening", "Buses are always faster than cars", "Cities should never build new roads"], correct: 1, subject: COMP, explanation: "The passage contrasts road widening (undone by induced demand) with a bus lane that raised ridership without widening." },
    { q: PASSAGE_5 + "According to the passage, what happened within two years of the road-widening?", options: ["Traffic speeds improved permanently", "Traffic speeds returned to about their pre-widening level despite more vehicles", "The road was narrowed again", "Public transport was shut down"], correct: 1, subject: COMP, explanation: "The passage states peak-hour speeds were back to where they had been before widening." },
    { q: PASSAGE_5 + "What does the passage call the phenomenon where extra road space attracts more drivers?", options: ["Traffic calming", "Induced demand", "Modal shift", "Peak shaving"], correct: 1, subject: COMP, explanation: "The passage names this 'induced demand'." },
    { q: PASSAGE_5 + "What was the effect of adding a dedicated bus lane, as per the passage?", options: ["Bus ridership fell", "Peak-hour bus ridership rose sharply", "The road needed to be widened anyway", "Traffic congestion worsened"], correct: 1, subject: COMP, explanation: "The passage states peak-hour bus ridership rose sharply after the dedicated lane was added." },
    { q: PASSAGE_5 + "The word 'arterial' in the passage most nearly refers to a road that is:", options: ["A minor residential lane", "A major route carrying heavy through-traffic", "A pedestrian-only street", "A temporary diversion"], correct: 1, subject: COMP, explanation: "An arterial road is a major route, consistent with it being described as congested and carrying heavy traffic." },
    { q: PASSAGE_5 + "What can be inferred about simply adding road capacity, based on the passage?", options: ["It always delivers lasting congestion relief", "It may not deliver lasting relief because more drivers are drawn in", "It has no effect on driver behaviour", "It reduces the number of vehicles on the road"], correct: 1, subject: COMP, explanation: "The passage's central example shows widening drew in enough extra traffic to erase the initial speed gains." },
    { q: PASSAGE_5 + "The comparison in the passage is primarily between:", options: ["Cars and bicycles", "Widening a road and adding a dedicated bus lane", "Old roads and new roads", "Peak hours and off-peak hours"], correct: 1, subject: COMP, explanation: "The passage compares the outcome of widening a road against adding a dedicated bus lane on the same stretch." },
    { q: PASSAGE_5 + "Which conclusion is best supported by the passage?", options: ["Road widening is always the best solution", "Dedicated transit infrastructure can increase transit use without widening the road", "Bus lanes make traffic worse", "Induced demand only affects buses"], correct: 1, subject: COMP, explanation: "The bus-lane example directly supports this conclusion, in contrast with the widening example." },
  ],
};
